#!/usr/bin/python3
import sys
import random

args = sys.argv
numWords = 4
numCaps = 0
numNums = 0
numSymbols = 0

for i in range(1,len(args)):
  if(args[i] == '-h'):
    print('''
usage: xkcdpwgen [-h] [-w WORDS] [-c CAPS] [-n NUMBERS] [-s SYMBOLS]
                
Generate a secure, memorable password using the XKCD method
                
optional arguments:
    -h, --help            show this help message and exit
    -w WORDS, --words WORDS
                          include WORDS words in the password (default=4)
    -c CAPS, --caps CAPS  capitalize the first letter of CAPS random words
                          (default=0)
    -n NUMBERS, --numbers NUMBERS
                          insert NUMBERS random numbers in the password
                          (default=0)
    -s SYMBOLS, --symbols SYMBOLS
                          insert SYMBOLS random symbols in the password
                          (default=0)
                          ''')
    break
  if(args[i] == '-w' or args[i] == '--words'):
    try:
      numWords = int(args[i+1])
      i+=1
    except:
      print('Number of words could not be parsed, defaulting to 4')
  if(args[i] == '-c' or args[i] == '--caps'):
    try:
      numCaps = int(args[i+1])
      i+=1
    except:
      print('Number of caps could not be parsed, defaulting to 0')
  if(args[i] == '-n' or args[i] == '--numbers'):
    try:
      numNums = int(args[i+1])
      i+=1
    except:
      print('Number of numbers could not be parsed, defaulting to 4')
  if(args[i] == '-s' or args[i] == '--symbols'):
    try:
      numSymbols = int(args[i+1])
      i+=1
    except:
      print('Number of symbols could not be parsed, defaulting to 4')

#doing stuff with the values now

#opening the file
f = open('corncob_lowercase.txt','r')
words = f.readlines()
f.close()

#cleaning newlines off of data
for i in range(len(words)):
  words[i] = words[i].strip()
if(numCaps > numWords):
  numCaps = numWords

#generating the password
passString = ''
symbolList = ['!','@','#','$','%','^','&','*','(',')','-','+','_','=','[',']','{','}','\\','|','`','~',';',':','\"','\'',',','.','<','>','?','/']
while(numWords != 0 or numNums != 0 or numSymbols != 0):
  randNum = random.randint(1,3)
  if(randNum == 1 and numWords != 0):
    if(random.random() < numCaps/numWords):
      passString = passString + words[random.randrange(0,len(words))].capitalize()
      numWords-=1
      numCaps-=1
    else:
      passString = passString + words[random.randrange(0,len(words))]
      numWords-=1
  if(randNum == 2 and numNums != 0):
    passString = passString + str(random.randint(1,9))
    numNums-=1
  if(randNum == 3 and numSymbols != 0):
    passString = passString + symbolList[random.randrange(0,len(symbolList))]
    numSymbols-=1
print(passString)

